DROP TABLE IF EXISTS history.uploaded_orders;

CREATE TABLE history.uploaded_orders (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    batch_id uuid NOT NULL,
    upload_timestamp timestamp with time zone DEFAULT now(),
    
    order_no text,
    package_no text,
    order_type text,
    order_mark text,
    package_type text,
    main_package_no text,
    invoice_no text,
    order_status text,
    marketplace_status text,
    marketplace text,
    marketplace_store text,
    bigseller_store_nickname text,
    seller_name text,
    username_buyer text,
    customer_code text,
    customer_name text,
    receiver_name text,
    phone_number text,
    post_code text,
    country text,
    province_state text,
    city text,
    district_area text,
    town text,
    shipping_address text,
    sku text,
    product_id text,
    product_name text,
    variation_name text,
    first_level_category text,
    secondary_category text,
    third_level_category text,
    quantity integer,
    price numeric,
    product_subtotal numeric,
    original_price numeric,
    merchant_sku text,
    title text,
    base_unit text,
    serial_number text,
    image_link text,
    to_allocate_deduct text,
    commodity_cost numeric,
    reference_price numeric,
    product_weight numeric,
    length numeric,
    width numeric,
    height numeric,
    shelf text,
    package_weight_g numeric,
    inspector text,
    salesperson text,
    stock_out text,
    stock_in text,
    shipping_warehouse text,
    buyer_designed_logistics text,
    shipping_option text,
    cargo_carry_method text,
    tracking_number text,
    shipping_fee numeric,
    shipping_fee_paid_by_seller numeric,
    seller_shipping_discount numeric,
    marketplace_shipping_discount numeric,
    order_total numeric,
    payment_method text,
    management_fee numeric,
    transaction_fee numeric,
    seller_discount numeric,
    marketplace_discount numeric,
    voucher numeric,
    store_voucher numeric,
    currency text,
    order_time timestamp with time zone,
    order_paid_time timestamp with time zone,
    valid_time timestamp with time zone,
    expire_time timestamp with time zone,
    packed_time timestamp with time zone,
    printed_time timestamp with time zone,
    order_shipped_time timestamp with time zone,
    transit_time timestamp with time zone,
    completed_time timestamp with time zone,
    cancel_time timestamp with time zone,
    cancellation_reason text,
    status_before_canceled text,
    buyer_message text,
    seller_note text,
    note_for_cs text,
    note_for_pick text,
    payment_channel text,
    vat numeric,
    service_fee numeric,
    cancel_initiator text,
    platform_order_no text,
    settlement_status text,
    settled_amount numeric,
    unsettled_amount numeric,
    credit_due_date timestamp with time zone,
    supplier_name text,
    supplier_code text,
    is_abnormal_order text
);

CREATE INDEX idx_uploaded_orders_batch_id ON history.uploaded_orders(batch_id);
CREATE INDEX idx_uploaded_orders_upload_timestamp ON history.uploaded_orders(upload_timestamp);
